### ISSUE TITLE
Increase line-spacing (hardcoded, for building locally)

### ISSUE THREAD

**Issue by bfulop** [JaySandhu/neovim-mac#12]
Hello,

First, thank you so much for this project! I've spent many weeks testing out most of the Neovim-GUI apps and terminal emulators, and I think I've finally found my peace with Neovim-Mac. It's the fastest Neovim client in my tests and has minimal memory footprint!

I've already removed font-smoothing from my local build, by changing these lines to `false` on `src/font.mm`:

```
    CGContextSetAllowsFontSmoothing(context.get(), false);
    CGContextSetShouldSmoothFonts(context.get(), false);
```

This gives me much crisper looking fonts. Without the extra boldening, I also get some extra spacing between the lines.

I would still like to increase the line-spacing, just a little bit more. 

Is there a simple way where I could hardcode this somewhere in the source code and rebuild Neovim-Mac with it? 

I tried to find something that would resemble this setting in the sources but no success so far. (I don't know the languages used for Neovim-Mac)

Thanks!

**Comment by JaySandhu** [comment]
Hey, thanks for using the project! I'd definitely want to add a configurable line spacing option in the future, but for now you can hardcode it in: https://github.com/JaySandhu/neovim-mac/blob/f1050ff1138e154db645fef1277144fc97287fe0/src/NVGridView.mm#L403-L444

This patch should work:

```
diff --git a/src/NVGridView.mm b/src/NVGridView.mm
index c90b31e..3e2d094 100644
--- a/src/NVGridView.mm
+++ b/src/NVGridView.mm
@@ -401,26 +401,28 @@ - (void)setFrameSize:(NSSize)newSize {
 }
 
 - (void)setFont:(const font_family&)font {
     fontFamily = font;
 
     CGFloat leading = floor(font.leading() + 0.5);
     CGFloat descent = floor(font.descent() + 0.5);
     CGFloat ascent = floor(font.ascent() + 0.5);
+    CGFloat lineSpacingAbove = 0;
+    CGFloat lineSpacingBelow = 0;
 
-    CGFloat cellHeight = leading + descent + ascent;
+    CGFloat cellHeight = leading + descent + ascent + lineSpacingAbove + lineSpacingBelow;
     CGFloat cellWidth = floor(font.width() + 0.5);
 
     cellSize.x = cellWidth;
     cellSize.y = cellHeight;
     backingCellSize = [self convertSizeFromBacking:NSMakeSize(cellWidth, cellHeight)];
 
     baselineTranslate.x = 0;
-    baselineTranslate.y = ascent;
+    baselineTranslate.y = ascent + lineSpacingAbove;
 
     CGFloat underlinePos = font.underline_position();
     uint16_t lineThickness = floor(font.underline_thickness() + 0.5);
     int16_t underlineTranslate;
 
     if (underlinePos >= 0) {
         underlineTranslate = floor(underlinePos + 0.5);
     } else {
```

Just change the values of `lineSpacingAbove` and `lineSpacingBelow` variables to something you like.

**Comment by bfulop** [comment]
Perfect! 🎉 

Thank you so much @JaySandhu for the fast reply!
