### ISSUE TITLE
Completely dysfunctional (black screen)

### ISSUE THREAD

**Issue by AcinonXDev** [JaySandhu/neovim-mac#13]
On my system (2020 MacBook Pro, M1 Pro processor) starting the application results in a black screen where using any menu command does nothing in the window. 
I'll try building it from source with Xcode and see if that fixes anything.

**Comment by AcinonXDev** [comment]
I build it from source with xcodebuild and it worked fine.

**Comment by JaySandhu** [comment]
Glad building from source fixed it. The prebuilt binaries are pretty out of date (and Intel only). I  haven't gotten around to upgrading to macOS Ventura yet, once I do that, I'll publish a release and upload an arm and x86 build.
