### ISSUE TITLE
make[2]: *** [lj_folddef.h] Segmentation fault: 11

### ISSUE THREAD

**Issue by marmalodak** [JaySandhu/neovim-mac#5]
I imagine that this is probably a bug in something you can't control, but here it is anyway.

    /Library/Developer/CommandLineTools/usr/bin/cc -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -g -O2 -fomit-frame-pointer -Wall  -fPIC -DLUA_USE_APICHECK -DLUA_USE_ASSERT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -U_FORTIFY_SOURCE  -DLUA_ROOT=\"/Users/john/projects/neovim-mac/build/neovim/.deps/usr\" -DLUA_MULTILIB=\"lib\" -fno-stack-protector   -c -o lj_opt_mem.o lj_opt_mem.c
    BUILDVM   lj_folddef.h
    host/buildvm -m folddef -o lj_folddef.h lj_opt_fold.c
    make[2]: *** [lj_folddef.h] Segmentation fault: 11
    make[2]: *** Deleting file `lj_folddef.h'
    make[1]: *** [src/luajit] Error 2
    ninja: build stopped: subcommand failed.
    make: *** [deps] Error 1

    ❯ xcode-select --version
    xcode-select version 2384.
    ❯ sw_vers
    ProductName:    macOS
    ProductVersion: 11.2.2
    BuildVersion:   20D80

**Comment by JaySandhu** [comment]
I can confirm the build is broken, mine failed in the same way, so it's not your build environment.

We're missing a bunch of [back ported v0.4 commits](https://github.com/neovim/neovim/commits/release-0.4) in our Neovim fork, some of those commits were doing build maintenance, I'm guessing that pulling in those changes will fix it. I'll get on that. 

Ideally, we should be building universal binaries now, so the whole build process needs to be reworked. Building Neovim and all its dependencies as universal binaries seems pretty daunting, might take a few days lol.
