### ISSUE TITLE
Filename not showing in title bar

### ISSUE THREAD

**Issue by sfsam** [JaySandhu/neovim-mac#6]
The active buffer's filename isn't shown in the title bar.  Only "NVIM" is shown. This is the release build v0.1 (1).

Title bar should display "[No Name] - NVIM":
<img width="588" alt="Screen Shot 2021-10-21 at 12 03 48 PM" src="https://user-images.githubusercontent.com/118104/138341051-7ad992b6-36b0-4fba-9d0a-06338a1599a3.png">

Title bar should display "vimrc (~/.vim) - NVIM":
<img width="588" alt="Screen Shot 2021-10-21 at 12 05 11 PM" src="https://user-images.githubusercontent.com/118104/138341059-967b95f3-77a3-4f0f-a172-a233145b64cf.png">

**Comment by JaySandhu** [comment]
I think this might be a configuration issue. You may have disabled the `title` option, or you have set a bad `titlestring`.

Would you mind posting the output of `:echo &title &titlestring`?

Try running:

```
set titlestring=
set title
```

That should fix it.

**Comment by sfsam** [comment]
The output of `:echo &title &titlestring` was `0`.
The output of `:set title?` is `notitle`.

Yes, running those 2 `set` commands fixed it. Thank you!

I also checked MacVim and nvim (terminal)...

The output of `:echo &title &titlestring` in MacVim is `1`.
The output of `:set title?` in MacVim is `title`.

The output of `:echo &title &titlestring` in nvim is `0`.
The output of `:set title?` in nvim is `notitle`.

If I do `:help title`, it says the default is off. Do I need to explicitly set `title` in my vimrc? Is MacVim doing this automatically?

**Comment by JaySandhu** [comment]
I believe it's a Neovim / Vim difference. 

Vim defaults `title` to on if it detects a GUI is running: 
https://github.com/vim/vim/blob/94e7d345c156a722bb161b73238c4ba1d27ec586/src/option.c#L1149-L1193

Neovim doesn't do this, instead the `title` option is always off by default. 

In MacVim, `has("gui_running") == true`,  so the `title` option gets enabled by default. 

> Do I need to explicitly set `title` in my vimrc? 

I'm afraid so. A `set title` line should suffice.

**Comment by sfsam** [comment]
Ah, I didn't realize this was a vim/nvim difference. Thank you!
