### ISSUE TITLE
Crash on launch v0.2

### ISSUE THREAD

**Issue by sfsam** [JaySandhu/neovim-mac#8]
I'm getting a crash on launch in NVWindowController.mm:
<img width="745" alt="Screen Shot 2022-07-28 at 5 04 02 PM" src="https://user-images.githubusercontent.com/118104/181637158-486374e1-af1f-49ca-ae99-4004ff1cf853.png">

A few lines up, if I change:
<img width="742" alt="Screen Shot 2022-07-28 at 5 10 30 PM" src="https://user-images.githubusercontent.com/118104/181638074-fdd9b827-e28e-43d5-956f-3329a509380f.png">

to:
<img width="747" alt="Screen Shot 2022-07-28 at 5 08 35 PM" src="https://user-images.githubusercontent.com/118104/181637821-782cba19-a150-4e71-b423-d8e08be1b165.png">

it launches successfully. I'm not sure, but I think ARC is deallocating the newly allocated NVTab without the CFBridgingRetain.

**Comment by JaySandhu** [comment]
Good catch, thanks! You're correct, ARC is defintely releasing that tab object when it goes out of scope. Adding an explicit retain without a corresponding release will cause leaks, so Ideally we want to transfer ownership to the `tabs` array and the `NVTabLine` object. I think https://github.com/JaySandhu/neovim-mac/commit/93f29defb2ac889d85be348bad0fe77d80ae4572 should fix it.

**Comment by sfsam** [comment]
Nice.
