### ISSUE TITLE
Copy (Command-C) doesn't work in Visual Block mode

### ISSUE THREAD

**Issue by sfsam** [JaySandhu/neovim-mac#9]
When I try to copy text with Command-C in Visual Block mode, I get a beep sound. It does work in Visual Character or Visual Line mode though. I think in the `-copy:` method, `nvim.get_mode()` is returning `unknown` instead of `visual_block`?

**Comment by sfsam** [comment]
I think the issue is in `to_mode()`. If you change the case for `visual_block` from `constant("CTRL-V")` to `constant("\u0016")` it will return `visual_mode`. "\u0016" is unicode point for Ctrl-V.

**Comment by JaySandhu** [comment]
Thanks for the bug report and the investigating. Can confirm the issue and that the suggested fix works. Wondering if this has always been broken, or if something changed in Neovim. I will look into it some more to see if any of the other mode strings are also wrong.

**Comment by JaySandhu** [comment]
Turns out it's been broken this whole time. I misread the docs for the `mode()` function, didn't realize that the `CTRL-` characters are one Unicode codepoint. I believe it's fixed now.

**Comment by sfsam** [comment]
Awesome. I'm very impressed with the work you've done. Admittedly, I don't understand most of it so it's a great opportunity to learn. Thanks for sharing it and I look forward to seeing where you take it.
